apiVersion: v1
kind: Config
current-context: default
contexts:
- name: default
  context:
    cluster: garden
    user: tooluser
    namespace: "{{ garden_namespace }}"
clusters:
- name: garden
  cluster:
    server: "{{ garden_api_server }}"
    certificate-authority-data: "{{ garden_ca_data }}"
users:
- name: tooluser
  user:
    token: "{{ garden_token }}"
