apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: '{{ name }}'
spec:
  clusterNetwork:
    services:
      cidrBlocks: ['10.128.0.0/12']
    pods:
      cidrBlocks: ['192.168.0.0/16']
    serviceDomain: 'cluster.local'
  topology:
    # the following variables can be determined automatically using autoVars: syself
    # for this detection, we list all clusterstackrelease objects and select the latest one that fits the
    # requested kubernetesVersion
    class: '{{ cs_class_name }}'
    version: '{{ cs_version }}'
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: workeramd64hcloud
          name: md-0
          replicas: 1
          failureDomain: nbg1
          variables:
            overrides:
              - name: workerMachineTypeHcloud
                value: cpx31
    variables:
      - name: region
        value: nbg1
      - name: controlPlaneMachineTypeHcloud
        value: cpx31
