apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMk1ERXhOakV3TlRFME5sb1hEVE0yTURFeE5ERXdOVFkwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlRvClFmeFN5R1BmeTVaRWdqV2NYSDErUlBBNU1KcUVwNC9lVEp0OTc5ajZrYTJaa296S3Q5YlJpTk1rRk4zSEhBQ2QKZEtucERhMk51ODVjSFBqQlJyeVl2ZjZHa2duYUpNQ3A2VUhpdnFFWFZwOU1SckVtTjlOZmZnMlozQmJxQ3h6awpRTHJuayt1WkxDb0RtVXl3WFpNRkFoMHVPeXVkcmhGSGxia0MzdFhPWk0rRGdzMHBXZFRjcjV5bnVudEtBeG9MCnE4MFhjQWYwaWtCMlFHanMyRkQvdWdIWE9WQnlkNmQxTkxsMyttN3JWbCtwaDQ2SUNESG1FY0tYWHBQbC83Z3EKc0FML2xyRnBqV0xIZi80a3JVemNUMUQvMG5jK1ZuRDBVNkMvNjBRdEl3THlLOEdDdU1XZ3VlRW9MTkMvN1VNVAp1b1JMUE5oRlNwY1FwRGJFVEhNQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSitMK2Yra1c1dXJHaERITlUySmxORDVFUnNETUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQzNvMnJsSkxPbGQvWVViVm1ycVVjNnY0aDlsUjdGUXE1L3FpNjlaVGVTVUNhegpqL2szVjQ4emltT2pZU1VseWY0WWtsV2tkTzdSUDdGbTNEWFkvclNCZWJkU1pMaTFSNk1yT0ZSeC9jSzFiaFY4Ck5mTjhzdUliT1NOZ0txTS9kUDc3aGlsRXRFYXl4MWE5UVVLemd6UHpPMitCK3pwRHpKMTVDeDU3dTV2YkV5WlgKVjdRSVlEamJTQThCWWYya1NGL0RBRFJzd3JmaDREbGloRnYrZDFDSnlHVXdHUW9qZzVXKzVDc1ZkNWw4MlhBZgpzdDYzVkRWeVpzNFZlVzF6ckpFTVB3VVVVZmxielFNdzgrRFEwa2RaZG5tODY2bmZiOWNVT1d0MEd3UjYyWDJZCmp4Nm1JK0lKMzdyQVcybTc2VGVDZmlycFl3eHZZN0FOVk5ObHNiZTUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://212.8.205.30:6443
  name: mgmt-bfe2-prod
contexts:
- context:
    cluster: mgmt-bfe2-prod
    namespace: scs-kaas-certification
    user: scs-kaas-certification
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: scs-kaas-certification
  user:
    token: '{{ token }}'
