---
- name: Run ADR syntax check tool and test script consistency check tool
  hosts: all
  tasks:
    - name: Run ADR syntax check script
      ansible.builtin.command:
        cmd: python3 Tests/chk_adrs.py Standards
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      register: result
      changed_when: true
      failed_when: result.rc != 0

    - ansible.builtin.debug:
        msg: "{{ result.stdout }} {{ result.stderr }}"
