---
- name: Run ADR syntax check tool and test script consistency check tool
  hosts: all
  tasks:
    - name: Run ADR syntax check script
      ansible.builtin.command:
        cmd: python3 /home/ubuntu/Tests/chk_adrs.py /home/ubuntu/Standards
      register: result
      changed_when: true
      failed_when: result.rc != 0

    - name: Run test script consistency check script
      ansible.builtin.command:
        cmd: python3 /home/ubuntu/Tests/iaas/flavor-naming/check-yaml.py /home/ubuntu/Tests/iaas
      register: result
      changed_when: true
      failed_when: result.rc != 0

    - ansible.builtin.debug:
        msg: "{{ result.stdout }} {{ result.stderr }}"
