---
- name: Run compliance check tool
  hosts: all
  tasks:
    - name: Run compliance script
      ansible.builtin.shell: >
        python3 ~/Tests/scs-test-runner.py --config ~/Tests/config.toml --debug run --preset {{ preset }} --output report.yaml
      changed_when: true

    - name: Copy result YAML
      ansible.builtin.synchronize:
        dest: "{{ zuul.executor.log_root }}/report.yaml"
        mode: pull
        src: "report.yaml"
        verify_host: true
        owner: no
        group: no

    - name: Return artifact URL
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "report.yaml"
                url: "report.yaml"
