---
- name: Run compliance check tool
  hosts: all
  tasks:
    - name: Run compliance script
      # write report.yaml into the proper directory so it will be transferred back by base job
      # -- this then works regardless of VM/pod
      ansible.builtin.command:
        cmd: >
          python3 Tests/scs-test-runner.py --config Tests/config.toml --debug
          run --preset {{ preset }}
          --output "{{ ansible_user_dir }}/zuul-output/artifacts/report.yaml"
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      changed_when: true

    - name: Return artifact URL
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "report.yaml"
                url: "report.yaml"
