---
- name: Run compliance check tool
  hosts: all
  tasks:
    - name: Run compliance script
      ansible.builtin.shell: |
        python3 ~/Tests/scs-compliance-check.py ~/Tests/scs-compatible-iaas.yaml -s {{ item }} -a os_cloud={{ item }} -o report-{{ item }}.yaml -C
        ssh-keygen -Y sign -f ~/id_subject -n report report-{{ item }}.yaml
        curl --data-binary @report-{{ item }}.yaml.sig --data-binary @report-{{ item }}.yaml -H "Content-Type: application/x-signed-yaml" -H "Authorization: Basic $auth" https://compliance.sovereignit.cloud/reports
      changed_when: true
      failed_when: false
      # ^^^ this task does not fail; the only failure would be if `report.yaml` didn't get produced,
      # but then the subsequent tasks would fail anyway
      environment:
        auth: "{{ clouds_conf.zuul_ci_basic_auth }}"
      loop: "{{ clouds }}"

    - name: Copy result YAML
      ansible.builtin.synchronize:
        dest: "{{ zuul.executor.log_root }}/{{ item }}-iaas.yaml"
        mode: pull
        src: "report-{{ item }}.yaml"
        verify_host: true
        owner: no
        group: no
      loop: "{{ clouds }}"

    - name: Return artifact URL
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ item }}-iaas.yaml"
                url: "{{ item }}-iaas.yaml"
      loop: "{{ clouds }}"
