---
- name: Copy scripts+data and install Python dependencies
  hosts: all
  roles:
    - role: ensure-pip  # https://zuul-ci.org/docs/zuul-jobs/latest/python-roles.html#role-ensure-pip
  tasks:
    - name: Install dependencies
      ansible.builtin.pip:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        requirements: "Tests/requirements.txt"
