clouds:
  gx-scs:
    auth:
      auth_url: https://api.gx-scs.sovereignit.cloud:5000
      username: "u500924-svc-standards"
      project_id: 3829cc7c8f034fc985f5055a1df6f247
      project_name: "p500924-scs-healthmonitor"
      user_domain_name: "d500924"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
