clouds:
  scs2:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://scs2.api.pco.get-cloud.io:5000
      application_credential_id: "f8f301ccf04047589afac62665227edd"
    region_name: "scs2"
    interface: "public"
    identity_api_version: 3
  pco-prod1:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod1.api.pco.get-cloud.io:5000
      application_credential_id: "22801bcede0746a192abec1805c8c4e5"
    region_name: "prod1"
    interface: "public"
    identity_api_version: 3
  pco-prod2:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod2.api.pco.get-cloud.io:5000
      application_credential_id: "df41234ebc334d2cb99c586e8ad0056d"
    region_name: "prod2"
    interface: "public"
    identity_api_version: 3
  pco-prod3:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod3.api.pco.get-cloud.io:5000
      application_credential_id: "f5864cd2b0ce4fb3ba9d7e4d5e6e0674"
    region_name: "prod3"
    interface: "public"
    identity_api_version: 3
  pco-prod4:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod4.api.pco.get-cloud.io:5000
      #project_id: 6a97f8c649d342429cbe5d0f943602b0
      application_credential_id: "d265546ca8ef47e99d743c67e1230897"
    region_name: "prod4"
    interface: "public"
    identity_api_version: 3
  wavestack:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://api.wavestack.de:5000
      application_credential_id: "4cc7d7eca878454993fbe5b0c8ffbd35"
    region_name: "MUC5"
    interface: "public"
    identity_api_version: 3
  regio-a:
    auth:
      auth_url: https://keystone.services.a.regiocloud.tech
      application_credential_id: "54e55bf72cea4545b0d1c528e863b3c0"
    region_name: "RegionA"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"
  artcodix:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    #region_name: "MUC"
    auth:
      auth_url: https://api.dc1.muc.cloud.cnds.io:5000/
      application_credential_id: "39a5bf194c6e4b0d8348d28e55136750"
      #project_id: 225a7363dab74b69aa1e3f744aced109
  poc-kdo:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://keystone.services.poc-kdo.fitko.sovereignit.cloud
      application_credential_id: "248684b7a3da4dc786fbe65592f165be"
    region_name: "RegionOne"
  poc-wgcloud:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    #region_name: default
    auth:
      auth_url: https://identity.l1a.cloudandheat.com/v3
      application_credential_id: "7ab4e3339ea04255bc131868974cfe63"
  scaleup-occ2:
    auth_type: v3applicationcredential
    auth:
      auth_url: https://keystone.occ2.scaleup.cloud
      application_credential_id: "5d2eea4e8bf8448092490b4190d4430a"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
  syseleven-dus2:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    region_name: dus2
    auth:
      auth_url: https://keystone.cloud.syseleven.net:5000/v3
      application_credential_id: s11auth
  syseleven-ham1:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    region_name: ham1
    auth:
      auth_url: https://keystone.cloud.syseleven.net:5000/v3
      application_credential_id: s11auth
