clouds:
  gx-scs:
    auth:
      auth_url: https://api.gx-scs.sovereignit.cloud:5000
      username: "u500924-svc-standards"
      project_id: 3829cc7c8f034fc985f5055a1df6f247
      project_name: "p500924-scs-healthmonitor"
      user_domain_name: "d500924"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
  pco-prod1:
    auth:
      auth_url: https://prod1.api.pco.get-cloud.io:5000
      username: "u500924-svc-standards"
      project_id: 204eba6723954d0d900d1144b4c9e48d
      project_name: "p500924-scs-healthmonitor"
      user_domain_name: "d500924"
    region_name: "prod1"
    interface: "public"
    identity_api_version: 3
  pco-prod2:
    auth:
      auth_url: https://prod2.api.pco.get-cloud.io:5000
      username: "u500924-svc-standards"
      project_id: 6e54c8e75b744902a4c5f4389cdb0529
      project_name: "p500924-scs-healthmonitor"
      user_domain_name: "d500924"
    region_name: "prod2"
    interface: "public"
    identity_api_version: 3
  pco-prod3:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod3.api.pco.get-cloud.io:5000
      application_credential_id: "fe66c4c8cd3b4ea08262424783e1c58f"
    region_name: "prod3"
    interface: "public"
    identity_api_version: 3
  pco-prod4:
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://prod4.api.pco.get-cloud.io:5000
      #project_id: 6a97f8c649d342429cbe5d0f943602b0
      application_credential_id: "11ecfb998b474b99ab044f5b20cb23d6"
    region_name: "prod4"
    interface: "public"
    identity_api_version: 3
  wavestack:
    auth:
      auth_url: https://api.wavestack.de:5000
      username: "scs-standards"
      project_id: 00de553df86949b49365baee6375fb5a
      project_name: "scs-standards"
      user_domain_name: "scs"
    region_name: "MUC5"
    interface: "public"
    identity_api_version: 3
  regio-a:
    auth:
      auth_url: https://keystone.services.a.regiocloud.tech
      application_credential_id: "54e55bf72cea4545b0d1c528e863b3c0"
    region_name: "RegionA"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"
  artcodix:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    #region_name: "MUC"
    auth:
      auth_url: https://api.dc1.muc.cloud.cnds.io:5000/
      application_credential_id: "39a5bf194c6e4b0d8348d28e55136750"
      #project_id: 225a7363dab74b69aa1e3f744aced109
  poc-kdo:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    auth:
      auth_url: https://keystone.services.poc-kdo.fitko.sovereignit.cloud
      application_credential_id: "248684b7a3da4dc786fbe65592f165be"
    region_name: "RegionOne"
  poc-wgcloud:
    interface: public
    identity_api_verion: 3
    auth_type: "v3applicationcredential"
    #region_name: default
    auth:
      auth_url: https://identity.l1.cloudandheat.com/v3
      application_credential_id: "b4844a0fb23247149997bf0ff2c0b156"
      #project_id: 9adb8fc81ba345178654cee5cb7f1464
