name: "Compliance IaaS v4 of wavestack"

on:
  # Trigger compliance check every day at 4:35 UTC
  schedule:
    - cron:  '35 4 * * *'
  # Trigger compliance check after Docker image has been built
  workflow_run:
    workflows: [Build and publish scs-compliance-check Docker image]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  check-wavestack:
    uses: ./.github/workflows/scs-compliance-check-with-application-credential.yml
    with:
      version: v4
      layer: iaas
      cloud: "wavestack"
      secret_name: "OS_ACSECRET_WAVESTACK"
    secrets: inherit
