name: Check links in Markdown files

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        # https://github.com/orgs/community/discussions/26738#discussioncomment-3253176
        check-modified-files-only: ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) && 'yes' || 'no' }}
        config-file: 'mlc_config.json'
        base-branch: 'main'
