---
name: Check markdown syntax

"on":
  push:
    paths:
      - '**.md'
      - .github/workflows/lint-markdown.yml

jobs:
  lint-markdown-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
