name: Check compliance of SCS cloud

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      layer:
        required: true
        type: string
      cloud:
        required: true
        type: string
      secret_name:
        required: true
        type: string

jobs:
  scs-compliance-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sovereigncloudstack/scs-compliance-check:main
    steps:
      - name: "Get clouds.yaml"
        run: "mkdir /etc/openstack && wget -P /etc/openstack https://raw.githubusercontent.com/sovereigncloudstack/standards/main/.github/scs-compliance-check/openstack/clouds.yaml"
      - name: "Create secure.yaml"
        run: |
          cat << EOF > /etc/openstack/secure.yaml
          clouds:
            ${{ inputs.cloud }}:
              auth:
                application_credential_secret: ${{ secrets[inputs.secret_name] }}
          EOF
      - name: "Run scs-compliance-check"
        run: "cd /scs-compliance && ./scs-compliance-check.py scs-compatible.yaml --version ${{ inputs.version }} ${{ inputs.layer }} -o result.yaml"
        env:
          OS_CLOUD: ${{ inputs.cloud }}
      - name: "Upload results"
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: /scs-compliance/result.yaml
